real_categories_ids_2nd = {
    0: "Rear End Collision",
    1: "Lane Reduction Road Merging",
    2: "Contact With Open Car Door",
    3: "Wrong Way Driving Centerline Violation",
    4: "Collision On Narrow Side Roads",
    5: "Overtaking Accident",
    6: "Lane Change Path Change",
    7: "Crossing Safety Zone",
    8: "Start After Stopping Accident",
    9: "Emergency Vehicle Accident",
    10: "Roads Of Equal Width",
    11: "Main Road And Side Road",
    12: "Stop Sign Exists In One Direction Only",
    13: "One Way Sign Exists In One Direction Only",
    14: "Changing Lanes Within Intersection",
    15: "Lanes Wide Enough For Two Vehicles Side By Side",
    16: "Turning Angle Less Than 90 Degrees",
    17: "Two Vehicles Turning Right Simultaneously",
    18: "Other Vehicle Enters From The Side",
    19: "Stop Sign Exists In One Direction Only",
    20: "Entering Roadway From Non Roadway Area",
    21: "Entering Non Roadway Area From Roadway",
    22: "Between Parking Area And Driveway",
    23: "Single Lane Roundabout",
    24: "Two Lane Roundabout",
    25: "Straight Road",
    26: "After Passing Vehicle Intersection",
    27: "Before Passing Vehicle Intersection",
    28: "Intersection Main Road And Side Road",
    29: "Intersection Same Width Roads",
    30: "Single Road No Centerline",
    31: "Sidewalk And Roadway",
    32: "No Separation Between Sidewalk And Roadway",
    33: "Pedestrian Only Road",
    34: "Non Roadway Area",
    35: "After Passing Vehicle Crosswalk",
    36: "Before Passing Vehicle Crosswalk",
    37: "Driving Lane And Passing Lane",
    38: "Driving Lane And Driving Lane",
    39: "Merging",
    40: "Parking Or Stopping",
    41: "Rear End Collision",
    42: "Falling Object",
    43: "Pedestrian",
    44: "Changing Lanes Onto Shoulder",
    45: "Accident Between Oncoming Motorcycle And Vehicle",
    46: "Lane Wide Enough For Both Car And Motorcycle",
    47: "Congested Road",
    48: "U Turn Zone",
    49: "Other Vehicle Enters From Opposite Direction",
    50: "Violation Of Road Markings",
    51: "Entering Non Roadway Area From Sidewalk",
    52: "Accident Between Oncoming Bicycle And Vehicle",
    53: "Leading And Following Vehicles",
    54: "Bicycle Crossing",
    55: "Lane Wide Enough For Both Car And Bicycle",
    56: "Bicycle Only Road",
    57: "Bicycle Only Lane",
    58: "Bicycle Priority Road",
    59: "Unprotected Left Turn Sign Present",
    60: "Traffic Light Exists Only For One Direction"
}

real_categories_ids_3rd = {
    0: "Rear End Collision With Preceding Vehicle 1st Accident Vehicle",
    1: "Rear End Collision By Following Vehicle",
    2: "Stopped Or Parked",
    3: "Going Straight On Main Road",
    4: "Going Straight",
    5: "Facing Each Other Going Straight",
    6: "Preceding Vehicle Going Straight",
    7: "Passing Over Centerline From Behind",
    8: "Illegal Passing Solid Line",
    9: "Following Vehicle Going Straight",
    10: "Simultaneous Lane Change",
    11: "Lane Change While Waiting In Congested Lane Side Collision",
    12: "Following Vehicle Going Straight Before Leaving Safety Zone",
    13: "Following Vehicle Going Straight After Leaving Safety Zone",
    14: "Departing After Stop",
    15: "Preceding Vehicle Lane Change",
    16: "Going Straight From The Right",
    17: "Going Straight From The Right Entered Later",
    18: "Going Straight From The Right Entered Earlier",
    19: "Going Straight From Left Road",
    20: "Going Straight From Right Road",
    21: "Right Turn",
    22: "Right Turn Entered Later",
    23: "Right Turn Entered Earlier",
    24: "Left Turn From Right Road",
    25: "Going Straight From Main Road",
    26: "Going Straight From Main Road Entered Later",
    27: "Going Straight From Main Road Entered Earlier",
    28: "Going Straight From Side Road Left",
    29: "Going Straight From Side Road Right",
    30: "Right Turn From Side Road",
    31: "Right Turn From Side Road Entered Later",
    32: "Right Turn From Side Road Entered Earlier",
    33: "Right Turn From Main Road",
    34: "Right Turn From Main Road Entered Later",
    35: "Right Turn From Main Road Entered Earlier",
    36: "Left Turn From Side Road",
    37: "Going Straight On Unmarked Road",
    38: "Going Straight Violating Stop Sign Left Road",
    39: "Going Straight Violating Stop Sign Right Road",
    40: "Right Turn Violating Stop Sign",
    41: "Going Straight Violating Stop Sign",
    42: "Left Turn Violating Stop Sign",
    43: "Going Straight Lane Change Inside Intersection",
    44: "Following Vehicle Going Straight Left Side Of Lane",
    45: "Following Vehicle Going Straight Right Side Of Lane",
    46: "Right Turn Right Lane",
    47: "Green Light Going Straight",
    48: "Green Light Going Straight Collided With Red Light Vehicle",
    49: "Yellow Light Going Straight Collided With Red Light Vehicle",
    50: "Yellow Light Going Straight",
    51: "Red Light Going Straight",
    52: "Green Left Turn Signal Left Turn Collided With Red Light Vehicle",
    53: "Yellow Light Left Turn Collided With Red Light Vehicle",
    54: "Going Straight From Side Road",
    55: "Left Turn From Main Road",
    56: "Going Straight On Roadway",
    57: "Going Straight In Passageway",
    58: "Roundabout Turn 2nd Lane",
    59: "Entering Roundabout 1st To 2nd Lane",
    60: "Roundabout Turn 1st Lane",
    61: "Lane Change 1st To 2nd Lane In Roundabout",
    62: "Pedestrian Crossing",
    63: "Red Light Started Crossing Hit During Red Light",
    64: "Red Light Started Crossing Hit During Green Or Flashing Green",
    65: "Green Light Started Crossing Hit During Green Or Flashing Green",
    66: "Started Crossing On Green Or Flashing Green Hit During Red Light",
    67: "Red Light Started Crossing Hit During Green Light",
    68: "Green Light Started Crossing Hit During Red Light",
    69: "Flashing Green Started Crossing Hit During Red Light",
    70: "Flashing Green Started Crossing Hit During Flashing Green",
    71: "Crossing Side Road",
    72: "Crossing Main Road",
    73: "Crossing Road",
    74: "Walking On Sidewalk",
    75: "Walking On Roadway Due To Construction Or Obstruction On Sidewalk",
    76: "Walking On Roadway Within 1m From Boundary Without Reason",
    77: "Walking On Roadway Over 1m From Boundary Without Reason",
    78: "Playing Lying Down Or Similar Behavior On Road",
    79: "Walking On Edge Of Road",
    80: "Walking On Center Of Road",
    81: "Walking On Pedestrian Only Road",
    82: "Crossing Within 3m Behind Reversing Vehicle",
    83: "Crossing More Than 3m Behind Reversing Vehicle",
    84: "Crossing Within 10m Of Crosswalk",
    85: "Green Light Crossing Within 10m Of Crosswalk",
    86: "Red Light Crossing Within 10m Of Crosswalk",
    87: "Crossing Within 10m Of Overpass Or Underpass",
    88: "Going Straight On Passing Lane",
    89: "Collided With Parked Vehicle In Lane",
    90: "Collided With Parked Vehicle On Shoulder",
    91: "Rear End Collision With Leading Vehicle",
    92: "Collision Avoidance Due To Falling Object",
    93: "Lane Change To Shoulder",
    94: "Crossing Centerline To Opposite Lane",
    95: "Following Overtake No Passing Zone",
    96: "Close Distance Overtake Dashed Centerline",
    97: "Lane Change",
    98: "Going Straight Side Collision",
    99: "U Turn",
    100: "Following Vehicle Just Before Collision",
    101: "Overtaking",
    102: "Going Straight From The Right Simultaneous Entry",
    103: "Going Straight From The Left Simultaneous Entry",
    104: "Going Straight From The Left Prior Entry",
    105: "Going Straight From The Left Later Entry",
    106: "Facing Each Other Left Turn",
    107: "Going Straight From The Left",
    108: "Left Turn From The Right",
    109: "Left Turn From The Left",
    110: "Right Turn From The Right Simultaneous Entry",
    111: "Right Turn From The Right Prior Entry",
    112: "Right Turn From The Right Later Entry",
    113: "Going Straight From Main Road Simultaneous Entry",
    114: "Going Straight From Side Road Simultaneous Entry",
    115: "Going Straight From Side Road Prior Entry",
    116: "Going Straight From Side Road Later Entry",
    117: "Right Turn From Side Road Simultaneous Entry",
    118: "Right Turn From Main Road Simultaneous Entry",
    119: "Left Turn On Unmarked Road",
    120: "Right Turn On Unmarked Road",
    121: "Straight In Violation Of One Way",
    122: "Following Vehicle Going Straight In Same Lane",
    123: "Preceding Vehicle Going Straight In Same Lane",
    124: "Preceding Vehicle Right Turn In Same Lane",
    125: "Preceding Vehicle Left Turn In Same Lane",
    126: "Overtaking Vehicle Right Turn In Same Lane",
    127: "Overtaking Vehicle Going Straight In Same Lane",
    128: "Following On Left Side Or Right Side Of Vehicle",
    129: "Preceding Left Turn From Right Side Or Right Turn From Left Side",
    130: "Straight Through Between Congested Lanes",
    131: "Left Turn On Red Light",
    132: "Left Turn On Yellow Light",
    133: "Going Straight Green Light Lane Change Inside Intersection",
    134: "Centerline Violation Overtake",
    135: "Left Turn On Green Left Turn Signal",
    136: "U Turn In Designated Area",
    137: "Signal Based U Turn",
    138: "Right Turn From Left Road",
    139: "U Turn Preceding",
    140: "Simultaneous U Turn Preceding",
    141: "Sharp U Turn Following",
    142: "Simultaneous U Turn Following",
    143: "Right Turn From Opposite Direction",
    144: "Following Vehicle Going Straight On Green Straight And Left Turn Lane",
    145: "Preceding Left Turn On Green Straight And Left Turn Lane",
    146: "Left Turn On Straight Lane Marking",
    147: "Straight On Straight And Left Turn Lane Marking",
    148: "Overtaking Right Turn On Straight Lane Marking",
    149: "Straight On Straight And Right Turn Lane Marking",
    150: "Entering Road From Non Road Area",
    151: "Entering Non Road Area From Road",
    152: "From Sidewalk To Non Road Area",
    153: "Turning Inside Intersection",
    154: "Entering Roundabout",
    155: "Entering Roundabout 2nd Lane To Roundabout 2nd Lane",
    156: "Large Scale Entry Into Roundabout",
    157: "Crossing The Roadway",
    158: "Wrong Way Driving Facing Vehicle",
    159: "Crossing Bicycle Crossing",
    160: "Going Straight Facing Vehicle",
    161: "Left Turn Facing Vehicle",
    162: "Right Turn From The Right",
    163: "Large Detour On Left Side Of Vehicle",
    164: "Small Detour On Left Side Of Vehicle",
    165: "Left Turn On Green Light Unprotected",
    166: "On Bicycle Only Road",
    167: "On Bicycle Only Lane",
    168: "On Bicycle Priority Road",
    169: "Going Straight Facing Vehicle On Red",
    170: "Going Straight Facing Vehicle On Green",
    171: "Going Straight Facing Vehicle On Yellow",
    172: "Left Turn Green Left Turn Collided With Red Light Facing Vehicle",
    173: "Left Turn Yellow Collided With Red Light Facing Vehicle",
    174: "Left Turn Green Unprotected Facing Vehicle",
    175: "Going Straight No Signal",
    176: "Right Turn No Signal",
    177: "Left Turn No Signal",
    178: "Going Straight On Green Left Turn Signal In Left Turn Lane",
    179: "Preceding Right Turn In Straight And Right Turn Lane"
}

real_categories_ids_4th = {
    0: "Rear End Collision With Preceding Vehicle 1st Accident Vehicle",
    1: "Rear End Collision By Following Vehicle",
    2: "Stopped Or Parked",
    3: "Going Straight On Main Road",
    4: "Going Straight",
    5: "Facing Each Other Going Straight",
    6: "Preceding Vehicle Going Straight",
    7: "Passing Over Centerline From Behind",
    8: "Illegal Passing Solid Line",
    9: "Following Vehicle Going Straight",
    10: "Simultaneous Lane Change",
    11: "Lane Change While Waiting In Congested Lane Side Collision",
    12: "Following Vehicle Going Straight Before Leaving Safety Zone",
    13: "Following Vehicle Going Straight After Leaving Safety Zone",
    14: "Departing After Stop",
    15: "Preceding Vehicle Lane Change",
    16: "Going Straight From The Right",
    17: "Going Straight From The Right Entered Later",
    18: "Going Straight From The Right Entered Earlier",
    19: "Going Straight From Left Road",
    20: "Going Straight From Right Road",
    21: "Right Turn",
    22: "Right Turn Entered Later",
    23: "Right Turn Entered Earlier",
    24: "Left Turn From Right Road",
    25: "Going Straight From Main Road",
    26: "Going Straight From Main Road Entered Later",
    27: "Going Straight From Main Road Entered Earlier",
    28: "Going Straight From Side Road Left",
    29: "Going Straight From Side Road Right",
    30: "Right Turn From Side Road",
    31: "Right Turn From Side Road Entered Later",
    32: "Right Turn From Side Road Entered Earlier",
    33: "Right Turn From Main Road",
    34: "Right Turn From Main Road Entered Later",
    35: "Right Turn From Main Road Entered Earlier",
    36: "Left Turn From Side Road",
    37: "Going Straight On Unmarked Road",
    38: "Going Straight Violating Stop Sign Left Road",
    39: "Going Straight Violating Stop Sign Right Road",
    40: "Right Turn Violating Stop Sign",
    41: "Going Straight Violating Stop Sign",
    42: "Left Turn Violating Stop Sign",
    43: "Going Straight Lane Change Inside Intersection",
    44: "Following Vehicle Going Straight Left Side Of Lane",
    45: "Following Vehicle Going Straight Right Side Of Lane",
    46: "Right Turn Right Lane",
    47: "Green Light Going Straight",
    48: "Green Light Going Straight Collided With Red Light Vehicle",
    49: "Yellow Light Going Straight Collided With Red Light Vehicle",
    50: "Yellow Light Going Straight",
    51: "Red Light Going Straight",
    52: "Green Left Turn Signal Left Turn Collided With Red Light Vehicle",
    53: "Yellow Light Left Turn Collided With Red Light Vehicle",
    54: "Going Straight From Side Road",
    55: "Left Turn From Main Road",
    56: "Going Straight On Roadway",
    57: "Going Straight In Passageway",
    58: "Roundabout Turn 2nd Lane",
    59: "Entering Roundabout 1st To 2nd Lane",
    60: "Roundabout Turn 1st Lane",
    61: "Lane Change 1st To 2nd Lane In Roundabout",
    62: "Pedestrian Crossing",
    63: "Red Light Started Crossing Hit During Red Light",
    64: "Red Light Started Crossing Hit During Green Or Flashing Green",
    65: "Green Light Started Crossing Hit During Green Or Flashing Green",
    66: "Started Crossing On Green Or Flashing Green Hit During Red Light",
    67: "Red Light Started Crossing Hit During Green Light",
    68: "Green Light Started Crossing Hit During Red Light",
    69: "Flashing Green Started Crossing Hit During Red Light",
    70: "Flashing Green Started Crossing Hit During Flashing Green",
    71: "Crossing Side Road",
    72: "Crossing Main Road",
    73: "Crossing Road",
    74: "Walking On Sidewalk",
    75: "Walking On Roadway Due To Construction Or Obstruction On Sidewalk",
    76: "Walking On Roadway Within 1m From Boundary Without Reason",
    77: "Walking On Roadway Over 1m From Boundary Without Reason",
    78: "Playing Lying Down Or Similar Behavior On Road",
    79: "Walking On Edge Of Road",
    80: "Walking On Center Of Road",
    81: "Walking On Pedestrian Only Road",
    82: "Crossing Within 3m Behind Reversing Vehicle",
    83: "Crossing More Than 3m Behind Reversing Vehicle",
    84: "Crossing Within 10m Of Crosswalk",
    85: "Green Light Crossing Within 10m Of Crosswalk",
    86: "Red Light Crossing Within 10m Of Crosswalk",
    87: "Crossing Within 10m Of Overpass Or Underpass",
    88: "Going Straight On Passing Lane",
    89: "Collided With Parked Vehicle In Lane",
    90: "Collided With Parked Vehicle On Shoulder",
    91: "Rear End Collision With Leading Vehicle",
    92: "Collision Avoidance Due To Falling Object",
    93: "Lane Change To Shoulder",
    94: "Crossing Centerline To Opposite Lane",
    95: "Following Overtake No Passing Zone",
    96: "Close Distance Overtake Dashed Centerline",
    97: "Lane Change",
    98: "Going Straight Side Collision",
    99: "U Turn",
    100: "Following Vehicle Just Before Collision",
    101: "Overtaking",
    102: "Going Straight From The Right Simultaneous Entry",
    103: "Going Straight From The Left Simultaneous Entry",
    104: "Going Straight From The Left Prior Entry",
    105: "Going Straight From The Left Later Entry",
    106: "Facing Each Other Left Turn",
    107: "Going Straight From The Left",
    108: "Left Turn From The Right",
    109: "Left Turn From The Left",
    110: "Right Turn From The Right Simultaneous Entry",
    111: "Right Turn From The Right Prior Entry",
    112: "Right Turn From The Right Later Entry",
    113: "Going Straight From Main Road Simultaneous Entry",
    114: "Going Straight From Side Road Simultaneous Entry",
    115: "Going Straight From Side Road Prior Entry",
    116: "Going Straight From Side Road Later Entry",
    117: "Right Turn From Side Road Simultaneous Entry",
    118: "Right Turn From Main Road Simultaneous Entry",
    119: "Left Turn On Unmarked Road",
    120: "Right Turn On Unmarked Road",
    121: "Straight In Violation Of One Way",
    122: "Following Vehicle Going Straight In Same Lane",
    123: "Preceding Vehicle Going Straight In Same Lane",
    124: "Preceding Vehicle Right Turn In Same Lane",
    125: "Preceding Vehicle Left Turn In Same Lane",
    126: "Overtaking Vehicle Right Turn In Same Lane",
    127: "Overtaking Vehicle Going Straight In Same Lane",
    128: "Following On Left Side Or Right Side Of Vehicle",
    129: "Preceding Left Turn From Right Side Or Right Turn From Left Side",
    130: "Straight Through Between Congested Lanes",
    131: "Left Turn On Red Light",
    132: "Left Turn On Yellow Light",
    133: "Going Straight Green Light Lane Change Inside Intersection",
    134: "Centerline Violation Overtake",
    135: "Left Turn On Green Left Turn Signal",
    136: "U Turn In Designated Area",
    137: "Signal Based U Turn",
    138: "Right Turn From Left Road",
    139: "U Turn Preceding",
    140: "Simultaneous U Turn Preceding",
    141: "Sharp U Turn Following",
    142: "Simultaneous U Turn Following",
    143: "Right Turn From Opposite Direction",
    144: "Following Vehicle Going Straight On Green Straight And Left Turn Lane",
    145: "Preceding Left Turn On Green Straight And Left Turn Lane",
    146: "Left Turn On Straight Lane Marking",
    147: "Straight On Straight And Left Turn Lane Marking",
    148: "Overtaking Right Turn On Straight Lane Marking",
    149: "Straight On Straight And Right Turn Lane Marking",
    150: "Entering Road From Non Road Area",
    151: "Entering Non Road Area From Road",
    152: "From Sidewalk To Non Road Area",
    153: "Turning Inside Intersection",
    154: "Entering Roundabout",
    155: "Entering Roundabout 2nd Lane To Roundabout 2nd Lane",
    156: "Large Scale Entry Into Roundabout",
    157: "Crossing The Roadway",
    158: "Wrong Way Driving Facing Vehicle",
    159: "Crossing Bicycle Crossing",
    160: "Going Straight Facing Vehicle",
    161: "Left Turn Facing Vehicle",
    162: "Right Turn From The Right",
    163: "Large Detour On Left Side Of Vehicle",
    164: "Small Detour On Left Side Of Vehicle",
    165: "Left Turn On Green Light Unprotected",
    166: "On Bicycle Only Road",
    167: "On Bicycle Only Lane",
    168: "On Bicycle Priority Road",
    169: "Going Straight Facing Vehicle On Red",
    170: "Going Straight Facing Vehicle On Green",
    171: "Going Straight Facing Vehicle On Yellow",
    172: "Left Turn Green Left Turn Collided With Red Light Facing Vehicle",
    173: "Left Turn Yellow Collided With Red Light Facing Vehicle",
    174: "Left Turn Green Unprotected Facing Vehicle",
    175: "Going Straight No Signal",
    176: "Right Turn No Signal",
    177: "Left Turn No Signal",
    178: "Going Straight On Green Left Turn Signal In Left Turn Lane",
    179: "Preceding Right Turn In Straight And Right Turn Lane"
}